<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260328164958 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE message_prive (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenu TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lu_par_destinataire BOOLEAN DEFAULT false NOT NULL, expediteur_id INT NOT NULL, destinataire_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2DB3B2610335F61 ON message_prive (expediteur_id)');
        $this->addSql('CREATE INDEX IDX_2DB3B26A4F84F6E ON message_prive (destinataire_id)');
        $this->addSql('ALTER TABLE message_prive ADD CONSTRAINT FK_2DB3B2610335F61 FOREIGN KEY (expediteur_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_prive ADD CONSTRAINT FK_2DB3B26A4F84F6E FOREIGN KEY (destinataire_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_3e207d3d60bb6fe6 RENAME TO IDX_339E112E60BB6FE6');
        $this->addSql('ALTER INDEX idx_3e207d3d7a45358c RENAME TO IDX_339E112E7A45358C');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE message_prive DROP CONSTRAINT FK_2DB3B2610335F61');
        $this->addSql('ALTER TABLE message_prive DROP CONSTRAINT FK_2DB3B26A4F84F6E');
        $this->addSql('DROP TABLE message_prive');
        $this->addSql('ALTER INDEX idx_339e112e7a45358c RENAME TO idx_3e207d3d7a45358c');
        $this->addSql('ALTER INDEX idx_339e112e60bb6fe6 RENAME TO idx_3e207d3d60bb6fe6');
    }
}
