<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260330000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create Evenement and InscriptionEvenement tables';
    }

    public function up(Schema $schema): void
    {
        // Create evenement table
        $this->addSql('CREATE TABLE evenement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, description TEXT NOT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lieu VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, capacite_max INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, createur_id INT NOT NULL, groupe_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D10B6E1873A201E5 ON evenement (createur_id)');
        $this->addSql('CREATE INDEX IDX_D10B6E187A45358C ON evenement (groupe_id)');
        
        // Create inscription_evenement table
        $this->addSql('CREATE TABLE inscription_evenement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_inscription TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, est_present BOOLEAN NOT NULL DEFAULT false, utilisateur_id INT NOT NULL, evenement_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A6D02E5FA76ED395 ON inscription_evenement (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_A6D02E5F4E1D8C2E ON inscription_evenement (evenement_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_utilisateur_evenement ON inscription_evenement (utilisateur_id, evenement_id)');
        
        // Add foreign keys to evenement
        $this->addSql('ALTER TABLE evenement ADD CONSTRAINT FK_D10B6E1873A201E5 FOREIGN KEY (createur_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE evenement ADD CONSTRAINT FK_D10B6E187A45358C FOREIGN KEY (groupe_id) REFERENCES groupe (id) NOT DEFERRABLE');
        
        // Add foreign keys to inscription_evenement
        $this->addSql('ALTER TABLE inscription_evenement ADD CONSTRAINT FK_A6D02E5FA76ED395 FOREIGN KEY (utilisateur_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inscription_evenement ADD CONSTRAINT FK_A6D02E5F4E1D8C2E FOREIGN KEY (evenement_id) REFERENCES evenement (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // Drop foreign keys
        $this->addSql('ALTER TABLE inscription_evenement DROP CONSTRAINT FK_A6D02E5FA76ED395');
        $this->addSql('ALTER TABLE inscription_evenement DROP CONSTRAINT FK_A6D02E5F4E1D8C2E');
        $this->addSql('ALTER TABLE evenement DROP CONSTRAINT FK_D10B6E1873A201E5');
        $this->addSql('ALTER TABLE evenement DROP CONSTRAINT FK_D10B6E187A45358C');
        
        // Drop tables
        $this->addSql('DROP TABLE inscription_evenement');
        $this->addSql('DROP TABLE evenement');
    }
}
