<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260318170013 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add MessageGroupe entity for group messaging';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE message_groupe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenu TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, auteur_id INT NOT NULL, groupe_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3E207D3D60BB6FE6 ON message_groupe (auteur_id)');
        $this->addSql('CREATE INDEX IDX_3E207D3D7A45358C ON message_groupe (groupe_id)');
        $this->addSql('ALTER TABLE message_groupe ADD CONSTRAINT FK_3E207D3D60BB6FE6 FOREIGN KEY (auteur_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE message_groupe ADD CONSTRAINT FK_3E207D3D7A45358C FOREIGN KEY (groupe_id) REFERENCES groupe (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE message_groupe DROP CONSTRAINT FK_3E207D3D60BB6FE6');
        $this->addSql('ALTER TABLE message_groupe DROP CONSTRAINT FK_3E207D3D7A45358C');
        $this->addSql('DROP TABLE message_groupe');
    }
}