<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260328204853 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE amitie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, statut VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user1_id INT NOT NULL, user2_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8FF9F39C56AE248B ON amitie (user1_id)');
        $this->addSql('CREATE INDEX IDX_8FF9F39C441B8B65 ON amitie (user2_id)');
        $this->addSql('ALTER TABLE amitie ADD CONSTRAINT FK_8FF9F39C56AE248B FOREIGN KEY (user1_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE amitie ADD CONSTRAINT FK_8FF9F39C441B8B65 FOREIGN KEY (user2_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE amitie DROP CONSTRAINT FK_8FF9F39C56AE248B');
        $this->addSql('ALTER TABLE amitie DROP CONSTRAINT FK_8FF9F39C441B8B65');
        $this->addSql('DROP TABLE amitie');
    }
}
